bank1/urls.py
from django.urls import path
from . import views
from blockchainkyc import settings
from django.conf.urls.static import static

app_name = "bank1"
urlpatterns = [
    path('login', views.bank_user_login, name = 'login'),
    path('approval', views.bank_approval, name = 'approval'),
    path('sendtoblockchain/<slug:kid>/',views.send_blockchain, name= 'sendtoblockchain'),
    path('documentrejected/<slug:kid>/', views.document_rejected, name='documentrejected'),
]

bank2/urls.py
from django.urls import path
from . import views
from blockchainkyc import settings
from django.conf.urls.static import static

app_name = "bank2"
urlpatterns = [
    path('login', views.bank_user_login, name = 'login'),
    path('search', views.usersearch, name = 'search'),
]

blockchainkyc/urls.py
from django.urls import path,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fileupload/', include('fileupload.urls', namespace="fileupload")),
    path('bank1/', include('bank1.urls', namespace="bank1")),
    path('bank2/',include('bank2.urls', namespace="bank2")),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

bank2/models.py
from django.db import models

# Create your models here.

bank2/views.py
from django.shortcuts import render
from django.contrib import messages
from fileupload.models import files_upload, User_Profile, status,notifications
from bank1.models import ipfsmapping
import ipfsapi


def bankauthenticate(username, password):
    if (username == "bankadmin"):
        return True


def bank_user_login(request):
    if request.method == 'POST':
        # Process the request if posted data are available
        username = request.POST['username']
        password = request.POST['password']
        # Check username and password combination if correct
        user = bankauthenticate(username=username, password=password)

        if user is True:
            # Save session as cookie to login the user
            # Success, now let's login the user
            user = User_Profile.objects.all()
            fu = files_upload.objects.all()
            statusf = status.objects.all()
            return render(request, 'search.html', {'user': user, 'fu': fu, 'status': statusf})
        else:
            # Incorrect credentials, let's throw an error to the screen.
            messages.error(request, 'username or password not correct')
            return render(request, 'b2login.html')
    else:
        # No post data availabe, let's just show the page to the user.
        return render(request, 'b2login.html')


def usersearch(request):
    if request.method == 'POST':
        uid = request.POST['username']


        api = ipfsapi.Client('127.0.0.1', 5001)
        try:
            u = User_Profile.objects.get(kycid=uid)
        except:
            messages.error(request, 'Userid ' + uid + ' is not valid KYC profile')
        else:
            nn = notifications.objects.get(nuid=u)

            if nn.approvestatus == "Accepted":
                files = {}
                messages.success(request, 'User ' + uid + ' has accepted your request to proceed with document verification and hence loading files from Blockchain')
                for n in ipfsmapping.objects.filter(userid=u.id).iterator():
                    print("Inside IPFS loop")
                    # print(n.ipfsid)
                    # res = api.cat(n.ipfsid)
                    # print(res)
                    # nam = res['name']
                    hashv = n.ipfsid
                    files[hashv] = n.fname
                return render(request, 'search.html', { 'files': files })
            else:

                nn.notify = "We (YesBank) would like to have access to review your documents"
                nn.approvestatus = "Approved"
                nn.save()
                messages.success(request, 'Notification sent to ' + uid + ' user to accept the review request')


        return render(request, 'search.html')

bank2/templates/b2login.html
<!DOCTYPE html>

{% load static %}

<html>
    <head>
        <title>Make Profile</title>
            <!-- Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- bootstrap theme -->
    <link href="{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">

    <!--external css-->
    <!-- font icon -->
    <link href="{% static 'css/elegant-icons-style.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">

    <link href="{% static 'css/jquery-jvectormap-1.2.2.css' %}" rel="stylesheet">

    <!-- Custom styles -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet">
    <link href="{% static 'css/jquery-ui-1.10.4.min.css' %}" rel="stylesheet">
    </head>
    <body>
    <!-- javascripts -->
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/jquery-ui-1.10.4.min.js' %}"></script>
<script src="{% static 'js/jquery-1.8.3.min.js' %}"></script>
<script src="{% static 'js/jquery-ui-1.9.2.custom.min.js' %}" type="text/javascript"></script>

<!-- bootstrap -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<!-- nice scroll -->
<script src="{% static 'js/jquery.scrollTo.min.js'%}"></script>
<script src="{% static 'js/jquery.nicescroll.js' %}"></script>

<!-- custom select -->
<script src="{% static 'js/jquery.customSelect.min.js' %}"></script>

<!--customer script for all page-->
<script src="{% static 'js/scripts.js' %}"></script>

<!-- custom script for this page-->
<script src="{% static 'js/jquery.autosize.min.js' %}"></script>
<script src="{% static 'js/jquery.placeholder.min.js' %}"></script>
<script src="{% static 'js/jquery.slimscroll.min.js' %}"></script>




{% block content %}
<div class="container" style="white-space:nowrap">
<div class="header">
<div style="background-image: url({% static 'img/whitebg.jpg' %});background-color: transparent; background-size: cover; align=left">
<div id="image" style="display:inline;">
<img src="{% static 'img/yesbank.png' %}" alt="Avatar" class="avatar" style="background-color: transparent;" >
</div>

</div>


    <div class="container">
    <center>
    <div style="background-image: url({% static 'img/glasscoin.jpg' %});background-color: transparent; background-size: cover">
    <form action="{% url 'bank2:login' %}" method="post">
            {% csrf_token %}

            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">

                    <div class="panel-body">
                        {% if error_message %}
                            <p class="bg-danger p-d ml-b">{{ error_message }}</p>
                        {% endif %}
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <h2><b> Enter your Credentials </b></h2>
                        <div class="form-group clearfix">
                            <label for="username" class="col-md-4 control-label text-right">Username:</label>
                            <br><div class="col-md-6">
                                <input name="username" value="" type="text" class="form-control" />
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="password" class="col-md-4 control-label text-right">Password:</label>
                            <br><div class="col-md-6">
                                <input name="password" type="password" class="form-control" />
                            </div>
                        </div>
                        <div class="col-md-6 col-md-offset-4">
                            <input name="login" type="submit" value="Login" class="btn btn-success" />
                        </div>
                        {% if messages %}
                         {% for message in messages %}

                    <div class="alert alert-success">
                        <a class="close" href="#" data-dismiss="alert">×</a>

                        {{ message }}


                    </div>
            {% endfor %}
            {% endif %}
                    </div>
                </div>
            </div>
                <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
     <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>

        </form>
    </div>
</div>


  </div>
  </form>
            </div>

        </center>
         </div>
         </div>
        {% endblock %}
    </body>
</html>

bank2/templates/search.html
<!DOCTYPE html>

{% load static %}
{% get_media_prefix as MEDIA_ROOT %}

<html>
    <head>
        <title>Make Profile</title>
            <!-- Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- bootstrap theme -->
    <link href="{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">

    <!--external css-->
    <!-- font icon -->
    <link href="{% static 'css/elegant-icons-style.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">

    <link href="{% static 'css/jquery-jvectormap-1.2.2.css' %}" rel="stylesheet">

    <!-- Custom styles -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet">
    <link href="{% static 'css/jquery-ui-1.10.4.min.css' %}" rel="stylesheet">
    </head>
    <body>
    <!-- javascripts -->
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/jquery-ui-1.10.4.min.js' %}"></script>
<script src="{% static 'js/jquery-1.8.3.min.js' %}"></script>
<script src="{% static 'js/jquery-ui-1.9.2.custom.min.js' %}" type="text/javascript"></script>

<!-- bootstrap -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<!-- nice scroll -->
<script src="{% static 'js/jquery.scrollTo.min.js'%}"></script>
<script src="{% static 'js/jquery.nicescroll.js' %}"></script>

<!-- custom select -->
<script src="{% static 'js/jquery.customSelect.min.js' %}"></script>

<!--customer script for all page-->
<script src="{% static 'js/scripts.js' %}"></script>

<!-- custom script for this page-->
<script src="{% static 'js/jquery.autosize.min.js' %}"></script>
<script src="{% static 'js/jquery.placeholder.min.js' %}"></script>
<script src="{% static 'js/jquery.slimscroll.min.js' %}"></script>




{% block content %}
<div class="container" style="white-space:nowrap">
<div class="header">
<div style="background-image: url({% static 'img/whitebg.jpg' %});background-color: transparent; background-size: cover; align=left">
<div id="image" style="display:inline;">
<img src="{% static 'img/yesbank.png' %}" alt="Avatar" class="avatar" style="background-color: transparent;" >
</div>

</div>


    <div class="container">
    <center>
    <form action="{% url 'bank2:search' %}" method="post">
            {% csrf_token %}

        {% if messages %}
                         {% for message in messages %}

                    <div class="alert alert-success">
                        <a class="close" href="#" data-dismiss="alert">×</a>

                        {{ message }}


                    </div>
            {% endfor %}
            {% endif %}

            {% if files %}
                {%  for k,v in files.items %}
                <img src="{{ MEDIA_ROOT }}uploads/{{ v }}" alt="Avatar" class="avatar" style="background-color: transparent;" >
                    <br>
                {%  endfor %}
            {% else %}
            <h2><b> Search a KYC profile </b></h2>
                         <div class="form-group clearfix">
                            <label for="username" class="col-md-4 control-label text-right"></label>
                            <br><div class="col-md-6">
                                <input name="username" value="" type="text" class="form-control" />
                            </div>
                        </div>
                        <div class="col-md-6 col-md-offset-4">
                            <input name="login" type="submit" value="Search" class="btn btn-success" />
                        </div>
            {%  endif %}
  </form>


        </center>
{% endblock %}
    </body>
</html>