bank1/urls.py
from django.urls import path
from . import views
from blockchainkyc import settings
from django.conf.urls.static import static

app_name = "bank1"
urlpatterns = [
    path('login', views.bank_user_login, name = 'login'),
    path('approval', views.bank_approval, name = 'approval'),
    path('sendtoblockchain/<slug:kid>/',views.send_blockchain, name= 'sendtoblockchain'),
    path('documentrejected/<slug:kid>/', views.document_rejected, name='documentrejected'),
]

blockchainkyc/urls.py
from django.urls import path,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fileupload/', include('fileupload.urls', namespace="fileupload")),
    path('bank1/', include('bank1.urls', namespace="bank1")),
    path('bank2/',include('bank2.urls', namespace="bank2")),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

fileupload/urls.py
from django.urls import path
from . import views
from blockchainkyc import settings
from django.conf.urls.static import static

app_name = "fileupload"
urlpatterns = [
    path('login', views.user_login, name = 'login'),
    path('upload/<slug:user>', views.upload, name= 'upload'),
    path('updatenotification/<slug:action>/<slug:kid>', views.updatenotification, name= 'updatenotification')
]

fileupload/models.py
from django.db import models

# Create your models here.

class User_Profile(models.Model):
    kycid = models.CharField(max_length=200,unique=True)
    fname = models.CharField(max_length=200)
    email = models.EmailField(default=None)
    display_picture = models.FileField(upload_to = 'uploads/')

    def __str__(self):
        return self.kycid


class files_upload(models.Model):
    filetype = models.CharField(max_length=200)
    filename = models.FileField(upload_to = 'uploads/')
    fileid = models.ForeignKey("User_Profile", on_delete=models.CASCADE)

    def __str__(self):
        return str(self.fileid)

class status(models.Model):
    uid = models.ForeignKey("User_Profile", on_delete=models.CASCADE,unique=True)
    status = models.CharField(max_length=200, default=None)

    def __str__(self):
        return str(self.uid)

class notifications(models.Model):
    nuid = models.ForeignKey("User_Profile", on_delete=models.CASCADE,unique=True)
    notify = models.CharField(max_length=800, default=None)
    approvestatus = models.CharField(max_length=200, default=None)

    def __str__(self):
        return str(self.nuid)

fileupload/forms.py
from django import forms

class ProfileForm(forms.Form):
   passp = forms.CharField(max_length = 100)
   passpic = forms.ImageFields()
   licen = forms.CharField(max_length=100)
   licenpic = forms.ImageFields()
   aadha = forms.CharField(max_length=100)
   aadhapic = forms.ImageFields()

fileupload/views.py
from django.shortcuts import render
from django.contrib import messages
from .models import files_upload,User_Profile,status, notifications
from django.conf import settings as confset

IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']

def authenticate(username):
    try:
        if (User_Profile.objects.get(kycid=username)):
            return True
    except:
        return False

def user_login(request):
    if request.method == 'POST':
        # Process the request if posted data are available
        username = request.POST['username']
        password = request.POST['password']
        # Check username and password combination if correct
        user = authenticate(username=username)
        if user is True:
            # Save session as cookie to login the user
            # Success, now let's login the user.
            user = User_Profile.objects.get(kycid=username)

            try:
                notification = notifications.objects.get(nuid=user)
            except:
                return render(request, 'fileupload.html', {'user': user})
            else:
                return render(request, 'fileupload.html', {'user': user, 'notification': notification})

        else:
            # Incorrect credentials, let's throw an error to the screen.
            messages.error(request,'username or password not correct')
            return render(request, 'login.html')
    else:
        # No post data availabe, let's just show the page to the user.
        return render(request, 'login.html')


def upload(request,user):
    username = user
    print(request)

    bank = request.POST['bank']
    passport = request.FILES['passport']
    license = request.FILES['license']
    print(bank ,' ', passport ,' ', license)

    u = User_Profile.objects.get(kycid=user)
    #confset.MEDIA_ROOT

    p = files_upload(fileid=u, filetype="Passport", filename=passport)
    p.save()
    s = files_upload(fileid=u, filetype="License", filename=license)
    s.save()

    messages.success(request, 'User documents are uploaded successfully !')
    return render(request, 'fileupload.html', {"user": u})

def updatenotification(request, action, kid):
    u = User_Profile.objects.get(kycid=kid)
    g = notifications.objects.get(nuid=u.id)

    if action == "accept":
        g.approvestatus = "Accepted"
        g.notify = "Your documents are under processing by YES bank as per your approval"
        g.save()
        messages.success(request, 'Thanks for approving the request , YesBank will process your documents from Blockchain!')
        return render(request, 'fileupload.html', {"user": u, "notification":g, "notificationstatus":1})

    elif action == "reject":
        g.approvestatus = "Reject"
        g.notify = "Your documents are not shared to YES bank as you rejected the request from YES bank"
        g.save()
        messages.error(request,'Thanks for responding the request , YesBank will not process your documents!!!')
        return render(request, 'fileupload.html', {"user": u, "notification": g, "notificationstatus": 0})
    else:
        return render(request, 'fileupload.html')

fileupload/templates/details.html
{% extends 'profile_maker/create.html' %}
{% block replace %}
<CENTER>
<div class="jumbotron">
  <h1 class="display-4">Welcome to DataFlair<br>Hello {{ user_pr.fname }}</h1>
  <p class="lead">its an awesome profile picture</p>
  <hr class="my-4">
  <img src="{{ user_pr.display_picture.url }}" class="image_responsive" height="100px" width="100px">
  <p>
    {{ user_pr.display_picture.url }}<BR>
   You have learned some awesome technologies like {{ user_pr.technologies }}</p>
</div>
</CENTER>
{% endblock %}

fileupload/templates/error.html
{% block replace %}
<CENTER>
    <h1 style = 'border: 5px red solid;'> hello, you have uploaded the wrong file type.</h1>
</CENTER>
{% endblock %}

fileupload/templates/fileupload.html
<!DOCTYPE html>

{% load static %}
{% get_media_prefix as MEDIA_ROOT %}

<html>
    <head>
        <title>Make Profile</title>
            <!-- Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- bootstrap theme -->
    <link href="{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">

    <!--external css-->
    <!-- font icon -->
    <link href="{% static 'css/elegant-icons-style.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">

    <link href="{% static 'css/jquery-jvectormap-1.2.2.css' %}" rel="stylesheet">

    <!-- Custom styles -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet">
    <link href="{% static 'css/jquery-ui-1.10.4.min.css' %}" rel="stylesheet">
        <style>

#uploadt {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 50%;
}

#uploadt td, #uploadt th {
  border: 1px solid #ddd;
  padding: 8px;
}

#uploadt tr:nth-child(n) {background-color: lightyellow }

#uploadt tr:hover {background-color: #ddd;}

#uploadt th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #4CAF50;
  color: white;
}
</style>

    </head>
    <body>
    <!-- javascripts -->
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/jquery-ui-1.10.4.min.js' %}"></script>
<script src="{% static 'js/jquery-1.8.3.min.js' %}"></script>
<script src="{% static 'js/jquery-ui-1.9.2.custom.min.js' %}" type="text/javascript"></script>

<!-- bootstrap -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<!-- nice scroll -->
<script src="{% static 'js/jquery.scrollTo.min.js'%}"></script>
<script src="{% static 'js/jquery.nicescroll.js' %}"></script>

<!-- custom select -->
<script src="{% static 'js/jquery.customSelect.min.js' %}"></script>

<!--customer script for all page-->
<script src="{% static 'js/scripts.js' %}"></script>

<!-- custom script for this page-->
<script src="{% static 'js/jquery.autosize.min.js' %}"></script>
<script src="{% static 'js/jquery.placeholder.min.js' %}"></script>
<script src="{% static 'js/jquery.slimscroll.min.js' %}"></script>



{% block content %}
<div></div>
<header>
<br>
<div style="background-image: url({% static 'img/449916.jpg' %});background-color: transparent; background-size: cover">
<span class="bold" ><h2>Welcome {{user.fname}} </h2><span>
<span class="bold" ><h3>KYC ID : {{user.kycid}} </h3><span>
<span class="bold" ><h3>Email ID : {{user.email}} </h3><span>
<img src="{{ MEDIA_ROOT }}{{user.display_picture}}"  width="50" height="50" hspace="10" alt="">

    <div class="container">

<br>
</header>


{% if notification %}
        {% if notificationstatus and notificationstatus == 1 %}
            <b> Thanks for approving the request , YesBank will process your documents from Blockchain! </b>
            {%  elif notificationstatus and notificationstatus == 0 %}
            <b> Thanks for responding the request , YesBank will not process your documents!!!</b>
            {%  elif notification.notify == "Your documents are successfully approved by ME bank and uploaded to Blockchain" %}
        <b>{{ notification.notify }}</b>
            {%  elif notification.notify == "Your documents are under processing by YES bank as per your approval" %}
             <b>{{ notification.notify }}</b>
            {%  else %}
            <b>{{ notification.notify }}</b>
          <input type="button" style="background-color:green;color:white;width:150px;height:40px;" value="Accept" onclick="location.href='{% url 'fileupload:updatenotification' action="accept" kid=user %}'">
         <input type="button" style="background-color:red;color:white;width:150px;height:40px;" value="Reject" onclick="location.href='{% url 'fileupload:updatenotification' action="reject" kid=user %}'">
          {% endif %}
 {% else %}

    {% if messages %}
                         {% for message in messages %}

                    <div class="alert alert-success">
                        <a class="close" href="#" data-dismiss="alert">×</a>

                        {{ message }}


                    </div>
            {% endfor %}
        {% else %}
        <h3> Complete your Profile </h3>
    <form action="{% url 'fileupload:upload' user=user %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
   <table id="uploadt">
    <tr>
        <th>Query</th>
        <th>selection</th>
   </tr>
       <tr>
   <td>
    <label for="bank"> Select Bank</label> </td>
           <td>

    <select name="bank" id="bank">
        <option value="NA">Select Bank</option>
        <option value="MeBank">MeBank</option>
        <option value="YesBank">YesBank</option>
    </select>
       </td>
       </tr>
    <br>
       <tr>
           <td>
               <label for="passport" class="col-md-4 control-label text-right">Passport</label>
           <td>

                            <br><div class="col-md-6">
                                <input type="file" name="passport" id="passport"/>
                            </div>
                        </div>
           </td>
    <br>
       <tr>
       <td>
           <label for="license" class="col-md-4 control-label text-right">License</label>
       <td>
    <br><div class="col-md-6">
                                <input type="file" name="license" id="license" />
                            </div>
           </td>
    <br>





   </table>
    <br>
     <button type="submit" style="background-color:#4CAF50;color:white;width:150px;height:40px;"><b>Submit</b></button>
            {% endif %}


    {%  endif %}

    </form>
</div>      

</body>
</html>
{% endblock %}

fileupload/templates/login.html
<!DOCTYPE html>

{% load static %}

<html>
    <head>
        <title>Make Profile</title>
            <!-- Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- bootstrap theme -->
    <link href="{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">

    <!--external css-->
    <!-- font icon -->
    <link href="{% static 'css/elegant-icons-style.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">

    <link href="{% static 'css/jquery-jvectormap-1.2.2.css' %}" rel="stylesheet">

    <!-- Custom styles -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet">
    <link href="{% static 'css/jquery-ui-1.10.4.min.css' %}" rel="stylesheet">
    </head>
    <body>
    <!-- javascripts -->
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/jquery-ui-1.10.4.min.js' %}"></script>
<script src="{% static 'js/jquery-1.8.3.min.js' %}"></script>
<script src="{% static 'js/jquery-ui-1.9.2.custom.min.js' %}" type="text/javascript"></script>

<!-- bootstrap -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<!-- nice scroll -->
<script src="{% static 'js/jquery.scrollTo.min.js'%}"></script>
<script src="{% static 'js/jquery.nicescroll.js' %}"></script>

<!-- custom select -->
<script src="{% static 'js/jquery.customSelect.min.js' %}"></script>

<!--customer script for all page-->
<script src="{% static 'js/scripts.js' %}"></script>

<!-- custom script for this page-->
<script src="{% static 'js/jquery.autosize.min.js' %}"></script>
<script src="{% static 'js/jquery.placeholder.min.js' %}"></script>
<script src="{% static 'js/jquery.slimscroll.min.js' %}"></script>


   

{% block content %}
<center>
<div style="background-image: url({% static 'img/whitebg1.jpg' %});background-color: transparent; background-size: cover">
    <div class="container">
<img src="{% static 'img/know-your-customer.png' %}" alt="Avatar" class="avatar" style="background-color: transparent;" >
        <form action="{% url 'fileupload:login' %}" method="post">
            {% csrf_token %}
            
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    
                    <div class="panel-body">
                        {% if error_message %}
                            <p class="bg-danger p-d ml-b">{{ error_message }}</p>
                        {% endif %}
                        <div class="form-group clearfix">
                            <label for="username" class="col-md-4 control-label text-right">Username:</label>
                            <br><div class="col-md-6">
                                <input name="username" value="" type="text" class="form-control" />
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="password" class="col-md-4 control-label text-right">Password:</label>
                            <br><div class="col-md-6">
                                <input name="password" type="password" class="form-control" />
                            </div>
                        </div>
                        <div class="col-md-6 col-md-offset-4">
                            <input name="login" type="submit" value="Login" class="btn btn-success" />
                        </div>
                        {% if messages %}
                         {% for message in messages %}

                    <div class="alert alert-success">
                        <a class="close" href="#" data-dismiss="alert">×</a>

                        {{ message }}
                        

                    </div>
            {% endfor %}
            {% endif %}
                    </div>
                </div>
            </div>
                <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
            <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>

            </center>
        </form>
    </div>
</div>


  </div>
  </form>
            </div>
       
        </center>
         </div>
        {% endblock %}
    </body>
</html>