bank1/urls.py
from django.urls import path
from . import views
from blockchainkyc import settings
from django.conf.urls.static import static

app_name = "bank1"
urlpatterns = [
    path('login', views.bank_user_login, name = 'login'),
    path('approval', views.bank_approval, name = 'approval'),
    path('sendtoblockchain/<slug:kid>/',views.send_blockchain, name= 'sendtoblockchain'),
    path('documentrejected/<slug:kid>/', views.document_rejected, name='documentrejected'),
]

blockchainkyc/urls.py
from django.urls import path,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fileupload/', include('fileupload.urls', namespace="fileupload")),
    path('bank1/', include('bank1.urls', namespace="bank1")),
    path('bank2/',include('bank2.urls', namespace="bank2")),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

bank1/models.py
from django.db import models
from fileupload.models import User_Profile
# Create your models here.

class ipfsmapping(models.Model):
    ipfsid = models.CharField(max_length=200)
    fname = models.CharField(max_length=200)
    userid = models.ForeignKey("fileupload.User_Profile", on_delete=models.CASCADE)

    def __str__(self):
        return str(self.userid)

bank1/views.py
from django.shortcuts import render
from django.contrib import messages
from fileupload.models import files_upload, User_Profile, status, notifications
from .models import ipfsmapping
import ipfsapi
import json
from web3 import Web3, HTTPProvider
#from solc import compile_files


def bankauthenticate(username, password):
    if (username == "bankadmin"):
        return True


def bank_user_login(request):
    if request.method == 'POST':
        # Process the request if posted data are available
        username = request.POST['username']
        password = request.POST['password']
        # Check username and password combination if correct
        user = bankauthenticate(username=username, password=password)

        if user is True:
            # Save session as cookie to login the user
            # Success, now let's login the user
            user = User_Profile.objects.all()
            fu = files_upload.objects.all()
            statusf = status.objects.all()
            return render(request, 'approvals.html', {'user': user, 'fu': fu, 'status': statusf})
        else:
            # Incorrect credentials, let's throw an error to the screen.
            messages.error(request, 'username or password not correct')
            return render(request, 'blogin.html')
    else:
        # No post data availabe, let's just show the page to the user.
        return render(request, 'blogin.html')


def bank_approval(request):
    return render(request, 'approvals.html')


#def smartcontract(hass):
 #   blockchain_address = 'http://127.0.0.1:9545'
  #  w3 = Web3(HTTPProvider(blockchain_address))
    # Set the default account (so we don't need to set the "from" for every transaction call)
    #w3.eth.defaultAccount = w3.eth.accounts[0]

    #compiled_sol = compile_files({
     #   "language": "Solidity",
      #  "sources": {
      #      "FixedSupplyToken.sol": {
      #          "urls": ["file:///Users/nithe/Documents/blockchain-eth/contracts/IPSFStoring.sol"]
      #      }
      #  }
    #}, allow_paths="file:///Users/nithe/Documents/blockchain-eth/contracts")

    #bytecode = compiled_sol['IPSFStoring.sol']
    #abi = json.loads(compiled_sol['IPSFStoring.sol'])['output']['abi']

    #hashing = w3.eth.contract(abi=abi, bytecode=bytecode)

    #tx_hash = hashing.constructor().transact()

    #tx_receipt = w3.eth.wait_for_transaction_receipt(tx_hash)

    #hasher  = w3.eth.contract(
     #   address=tx_receipt.contractAddress,
      #  abi=abi
    #)

    #m = hasher.functions.sendHash(hass).transact()
    #print(m)

    #tx_receipt = w3.eth.wait_for_transaction_receipt(tx_hash)

    #n = hasher.functions.getHash().call()

    #print(n)

def send_blockchain(request, kid):
    # This means the documents are APPROVED and sending to BlockChain
    api = ipfsapi.Client('127.0.0.1', 5001)
    u = User_Profile.objects.get(kycid=kid)

    for n in files_upload.objects.filter(fileid=u.id).iterator():
        res = api.add(n.filename)
        print(res)
        #hass = res['Hash']
        #smartcontract(hass)
        #{'Name': 'BeanPassport_SCj0aO4.jpg', 'Hash': 'QmShUEVGiypjngeqLdsmMVz41ScZYd9RJPNH8noK6MeMY2', 'Size': '12402'}
        #{'Name': 'BeanDrivingLicense.jpg', 'Hash': 'QmNqdfkB5f6A3gJJUSnA1scmZVmChj7BxG6JqbeLJyo2aA', 'Size': '138461'}

        w = ipfsmapping(ipfsid=res['Hash'],fname=res['Name'],userid=u)
        w.save()

    s = status(uid=u, status="Approved")
    s.save()

    try:
        nn = notifications(nuid=u, notify="Your documents are successfully approved and uploaded to Blockchain", approvestatus="Approved")
        nn.save()
    except:
        g = notifications.objects.get(nuid=u.id)
        g.notify="Your documents are successfully approved and uploaded to Blockchain"
        g.approvestatus="Approved"

    messages.success(request, 'User ' + kid + ' documents are approved and uploaded to IPSF, and also the user is notified ')
    user = User_Profile.objects.all()
    fu = files_upload.objects.all()
    statuf = status.objects.all()

    return render(request, 'approvals.html', {'user': user, 'fu': fu, 'status': statuf})


def document_rejected(request, kid):
    u = User_Profile.objects.get(kycid=kid)
    s = status(uid=u, status="Rejected")
    s.save()
    messages.success(request, 'User ' + kid + ' documents are rejected !!! ')
    user = User_Profile.objects.all()
    fu = files_upload.objects.all()
    statuf = status.objects.all()

    nn = notifications(nuid=u, notify="Your documents are rejected, please recheck the documents", approvestatus="Rejected")
    nn.save()

    try:
        nn = notifications(nuid=u, notify="Your documents are rejected, please recheck the documents", approvestatus="Rejected")
        nn.save()
    except:
        g = notifications.objects.get(nuid=u.id)
        g.notify="Your documents are rejected, please recheck the documents"
        g.approvestatus="Rejected"

    return render(request, 'approvals.html', {'user': user, 'fu': fu, 'status': statuf})

bank1/templates/approvals.html
<!DOCTYPE html>

{% load static %}

{% get_media_prefix as MEDIA_ROOT %}
<html>
    <head>
        <title>Make Profile</title>
            <!-- Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- bootstrap theme -->
    <link href="{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">

    <!--external css-->
    <!-- font icon -->
    <link href="{% static 'css/elegant-icons-style.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">

    <link href="{% static 'css/jquery-jvectormap-1.2.2.css' %}" rel="stylesheet">

    <!-- Custom styles -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet">
    <link href="{% static 'css/jquery-ui-1.10.4.min.css' %}" rel="stylesheet">

<style>

#customers {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

#customers tr:nth-child(n) {background-color: lightyellow }

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #4CAF50;
  color: white;
}
</style>

    </head>

    
    <body>
    <!-- javascripts -->
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/jquery-ui-1.10.4.min.js' %}"></script>
<script src="{% static 'js/jquery-1.8.3.min.js' %}"></script>
<script src="{% static 'js/jquery-ui-1.9.2.custom.min.js' %}" type="text/javascript"></script>

<!-- bootstrap -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<!-- nice scroll -->
<script src="{% static 'js/jquery.scrollTo.min.js'%}"></script>
<script src="{% static 'js/jquery.nicescroll.js' %}"></script>

<!-- custom select -->
<script src="{% static 'js/jquery.customSelect.min.js' %}"></script>

<!--customer script for all page-->
<script src="{% static 'js/scripts.js' %}"></script>

<!-- custom script for this page-->
<script src="{% static 'js/jquery.autosize.min.js' %}"></script>
<script src="{% static 'js/jquery.placeholder.min.js' %}"></script>
<script src="{% static 'js/jquery.slimscroll.min.js' %}"></script>

{% block content %}
<div class="container" style="white-space:nowrap">
<div class="header">
<div style="background-image: url({% static 'img/whitebg.jpg' %});background-color: transparent; background-size: cover; align=left">
<div id="image" style="display:inline;">
<img src="{% static 'img/mebank.png' %}" alt="Avatar" class="avatar" style="background-color: transparent;" >
</div>
  
</div>
</div>
</div>

<div class="container">
<form action="{% url 'bank1:approval' %}" method="post">
{% csrf_token %}
          

<div class="nameo">
 <h2 style="text-align:center"><b> KYC Documents for Approval </b></h2>
</div>
{% if messages %}
                         {% for message in messages %}

                    <div class="alert alert-success">
                        <a class="close" href="#" data-dismiss="alert"></a>

                        <b> {{ message }} </b>


                    </div>
            {% endfor %}
            {% endif %}
 <table id="customers">
    <tr>
        <th>KYC ID</th>
        <th>Full Name</th>
        <th>File Type</th>
        <th>File Name</th>
        <th>Status</th>
        <th>Approve/Reject</th>
    </tr>
    {% for us in user %}
    <tr> 
         <td> {{ us.kycid }} </td> <br>
         <td> {{ us.fname }} </td> <br>
           <td>
         {% for  ss in fu %}
        {% if ss.fileid|stringformat:"s" == us.kycid %}
        {{ ss.filetype}}, 
         {% endif %}

         {% endfor %}
         </td>
         <td>
         {% for  ss in fu %}
         {% if ss.fileid|stringformat:"s" == us.kycid %}
          <br><a href="{{ MEDIA_ROOT }}{{ss.filename}}"><span>{{ss.filename }}</span></a> <br>
        {% endif %}
         {% endfor %}
         </td>

         <td>
         {% for state in status %}


         {% if state.uid|stringformat:"s" == us.kycid %}
         {{ state.status }}
         {% endif %}
         {% endfor %}
         </td>

    <td>


             <input type="button" style="background-color:green;color:white;width:150px;height:40px;" value="Approve" onclick="location.href='{% url 'bank1:sendtoblockchain' kid=us.kycid %}'">
        <br>
        <br>
         <input type="button" style="background-color:red;color:white;width:150px;height:40px;" value="Reject" onclick="location.href='{% url 'bank1:documentrejected' kid=us.kycid %}'">
        <br>

         </td>


        
    
      
        
    </tr>
    
  
    {% endfor %}
</table>

   

         </div>
        {% endblock %}
         </form>
    </body>
</html>

bank1/templates/blogin.html
<!DOCTYPE html>

{% load static %}

<html>
    <head>
        <title>Make Profile</title>
            <!-- Bootstrap CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- bootstrap theme -->
    <link href="{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">

    <!--external css-->
    <!-- font icon -->
    <link href="{% static 'css/elegant-icons-style.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">

    <link href="{% static 'css/jquery-jvectormap-1.2.2.css' %}" rel="stylesheet">

    <!-- Custom styles -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet">
    <link href="{% static 'css/jquery-ui-1.10.4.min.css' %}" rel="stylesheet">
    </head>
    <body>
    <!-- javascripts -->
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/jquery-ui-1.10.4.min.js' %}"></script>
<script src="{% static 'js/jquery-1.8.3.min.js' %}"></script>
<script src="{% static 'js/jquery-ui-1.9.2.custom.min.js' %}" type="text/javascript"></script>

<!-- bootstrap -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<!-- nice scroll -->
<script src="{% static 'js/jquery.scrollTo.min.js'%}"></script>
<script src="{% static 'js/jquery.nicescroll.js' %}"></script>

<!-- custom select -->
<script src="{% static 'js/jquery.customSelect.min.js' %}"></script>

<!--customer script for all page-->
<script src="{% static 'js/scripts.js' %}"></script>

<!-- custom script for this page-->
<script src="{% static 'js/jquery.autosize.min.js' %}"></script>
<script src="{% static 'js/jquery.placeholder.min.js' %}"></script>
<script src="{% static 'js/jquery.slimscroll.min.js' %}"></script>


   

{% block content %}
<div class="container" style="white-space:nowrap">
<div class="header">
<div style="background-image: url({% static 'img/whitebg.jpg' %});background-color: transparent; background-size: cover; align=left">
<div id="image" style="display:inline;">
<img src="{% static 'img/mebank.png' %}" alt="Avatar" class="avatar" style="background-color: transparent;" >
</div>
  
</div>


    <div class="container">
    <center>
    <div style="background-image: url({% static 'img/unnamed.jpg' %});background-color: transparent; background-size: cover">
    <form action="{% url 'bank1:login' %}" method="post">
            {% csrf_token %}
            
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    
                    <div class="panel-body">
                        {% if error_message %}
                            <p class="bg-danger p-d ml-b">{{ error_message }}</p>
                        {% endif %}
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <br>
                        <h2><b> Enter your Credentials </b></h2>
                        <div class="form-group clearfix">
                            <label for="username" class="col-md-4 control-label text-right">Username:</label>
                            <br><div class="col-md-6">
                                <input name="username" value="" type="text" class="form-control" />
                            </div>
                        </div>
                        <div class="form-group clearfix">
                            <label for="password" class="col-md-4 control-label text-right">Password:</label>
                            <br><div class="col-md-6">
                                <input name="password" type="password" class="form-control" />
                            </div>
                        </div>
                        <div class="col-md-6 col-md-offset-4">
                            <input name="login" type="submit" value="Login" class="btn btn-success" />
                        </div>
                        {% if messages %}
                         {% for message in messages %}

                    <div class="alert alert-success">
                        <a class="close" href="#" data-dismiss="alert">×</a>

                        {{ message }}
                        

                    </div>
            {% endfor %}
            {% endif %}
                    </div>
                </div>
            </div>
                <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
     <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
           
        </form>
    </div>
</div>


  </div>
  </form>
            </div>
       
        </center>
         </div>
         </div>
        {% endblock %}
    </body>
</html>